export let reconect = document.getElementById('reconect-container')
export let audioElement = document.getElementById('audioId')
export let btn_play_pause = document.getElementById('bx-btn-play-pause')
export let btn_mute = document.getElementById('bx-btn-muteOnOff')
export let btn_reset = document.getElementById('bx-btn-reset')
export let parrafo_event = document.getElementById('parrafo-events')
export let slider = document.getElementById('slider')